[package]
name = "py-geopolars"
version = "0.1.0-alpha.1"
edition = "2021"
# Specify SPDX expression here instead of in pyproject.toml
# https://maturin.rs/metadata.html#add-spdx-license-expressions
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "geopolars"
crate-type = ["cdylib"]

[dependencies]
polars = {version = "0.22.8", default-features = false}
pyo3 = { version = "0.16.4", features = ["extension-module"] }
geopolars = { path = "../geopolars" }
thiserror = "1.0"
geo = { git = "https://github.com/georust/geo.git", rev = '578e213875915e1f895892487b5a36ca0d91fac3' }

[package.metadata.maturin]
python-source = "python"

[patch.crates-io]
chrono = { path = '../vendor/chrono' }
